name: dispatch receiver

on:
  repository_dispatch:
    types:
      - auto_publish
  workflow_dispatch:

jobs:
  upgrade: # upgrades package files with new JBrowse version
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event.client_payload.version }}
      - name: Upgrade dash_jbrowse version
        uses: actions/checkout@v4
      - run: |
          sed -i 's|.*dash-jbrowse.*|    "dash-jbrowse>=${{github.event.client_payload.version}}",|' requirements.txt
      - name: Commit and push changes
        run : |
          git config --global user.name "carolinebridge-oicr"
          git config --global user.email "cbridge@oicr.on.ca"
          git add -A
          git commit -m "Upgrading dash_jbrowse version"
          git push
      - name: Bump version
        uses: MeilCli/bump-release-action@v1
        with:
          config_path: '.github/bump.yml'
          bump: 'patch'
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: dispatch trigger
      run: |
        echo 'hello, world'
